const investProductTypeMapping = [
    {
        key : 'Ordinary Shares',
        fields : [
            {
                name: 'numberOfShares',
                label: 'Number of shares on issue',
                help: 'What is the total number of shares on offer?',
                placeholder: '',
                type: 'text',
                required: true,
                disabled: false,
            },
            {
                name: 'valuation',
                label: 'Valuation',
                help: 'What is your pre-money valuation for this raise?',
                helpLink : `https://${window.location.host}/articles/module/Wholesale-Intended-Raise#valuation`,
                helpLinkText : 'How to Value your Company.',
                placeholder: '',
                type: 'currency',
                required: false,
                disabled: false,
            },
            {
                name: 'wholesaleSharePrice',
                label: 'Share price',
                help: 'Your share price can be calculated by dividing your company\'s valuation by the total number of shares outstanding or available for investment',
                type: 'currency',
                placeholder: '',
                required: true,
                disabled: false,
            },
            {
                name: 'sharePriceCurrency',
                label: 'Share price currency',
                help: 'What currency is your share price in?',
                type: 'dropdown',
                placeholder: '',
                options: [
                    { label: 'AUD', value: 'AUD' },
                    { label: 'USD', value: 'USD' },
                ],
                required: true,
                disabled: false,
            }
        ]
    },
    {
        key : 'Preference Shares',
        fields : [
            {
                name: 'couponRate',
                label: 'Coupon rate (%)',
                help: 'Enter the fixed annual interest rate paid on the share\'s facevalue to investors.',
                type: 'number',
                placeholder: '%',
                required: false,
                disabled: false,
            },
            {
                name: 'term',
                label: 'Term (Months)',
                help: 'Specify the number of months until the preference shares convert into equity or mature.',
                type: 'number',
                placeholder: 'Months',
                required: false,
                disabled: false,
            },
            {
                name: 'dividendOption',
                label: 'Dividend option',
                help: 'Describe when and how dividends are paid to investors.',
                type: 'text',
                placeholder: '',
                required: true,
                disabled: false,
            },
            {
                name: 'redemption',
                label: 'Redemption',
                help: 'Describe who can elect to redeem and on what conditions.',
                type: 'text',
                placeholder: '',
                required: true,
                disabled: false,
            },
            {
                name: 'conversionTerms',
                label: 'Conversion terms',
                help: 'Detail the conditions and timing for converting the preference shares into equity, including any formulas or specific valuation methods.',
                type: 'textarea',
                placeholder: '',
                required: true,
                disabled: false,
            },
            {
                name: 'pricePerShare',
                label: 'Price per share',
                help: 'This information is for VentureCrowd and our agreement with you. It will not feature on your live Deal page.',
                type: 'currency',
                placeholder: '',
                required: true,
                disabled: false,
            },
        ]
    },
    {
        key : 'Convertible Note',
        fields : [
            {
                name: 'couponRate',
                label: 'Coupon rate (%)',
                help: 'Enter the fixed annual interest rate paid on the share\'s facevalue to investors.',
                type: 'number',
                placeholder: '%',
                required: false,
                disabled: false,
            },
            {
                name: 'term',
                label: 'Term (Months)',
                help: 'Specify the number of months until the convertible note converts or matures.',
                type: 'number',
                placeholder: 'Months',
                required: false,
                disabled: false,
            },
            {
                name: 'dividendOption',
                label: 'Dividend option',
                help: 'Describe when and how dividends are paid to investors.',
                type: 'text',
                placeholder: '',
                required: true,
                disabled: false,
            },
            {
                name: 'redemption',
                label: 'Redemption',
                help: 'Describe who can elect to redeem and on what conditions.',
                type: 'text',
                placeholder: '',
                required: true,
                disabled: false,
            },
            {
                name: 'conversionTerms',
                label: 'Conversion terms',
                help: 'Describe when and how the convertible note will convert.',
                type: 'textarea',
                placeholder: '',
                required: true,
                disabled: false,
            },
            {
                name: 'pricePerNote',
                label: 'Price per note',
                help: 'This information is for VentureCrowd and our agreement with you. It will not feature on your live Deal page.',
                type: 'currency',
                placeholder: '',
                required: true,
                disabled: false,
            },
        ]
    },
    {
        key : 'Promissory Note',
        fields : [
            {
                name: 'interestRate',
                label: 'Interest rate (%)',
                help: 'Enter the interest rate payable on the note.',
                type: 'number',
                placeholder: '%',
                required: false,
                disabled: false,
            },
            {
                name: 'term',
                label: 'Term (Months)',
                help: 'Specify the number of months until the promissory note matures.',
                type: 'number',
                placeholder: 'Months',
                required: false,
                disabled: false,
            },
            {
                name: 'security',
                label: 'Security',
                help: 'Indicate whether the note is secured or unsecured.',
                type: 'text',
                placeholder: '',
                required: true,
                disabled: false,
            },
            {
                name: 'pricePerNote',
                label: 'Price per note',
                help: 'This information is for VentureCrowd and our agreement with you. It will not feature on your live Deal page.',
                type: 'currency',
                placeholder: '',
                required: true,
                disabled: false,
            },
        ]
    },
    {
        key : 'SAFE Note',
        fields : [
            {
                name: 'valuationCap',
                label: 'Valuation cap',
                help: 'Please insert the valuation cap that applies to these notes.',
                type: 'currency',
                required: false,
                disabled: false,
            },
            {
                name: 'discountRate',
                label: 'Discount rate (%)',
                help: 'Please insert the discount rate that applies to these notes.',
                type: 'number',
                placeholder: '%',
                required: false,
                disabled: false,
            },
            {
                name: 'pricePerNote',
                label: 'Price per note',
                help: 'This information is for VentureCrowd and our agreement with you. It will not feature on your live Deal page.',
                type: 'currency',
                placeholder: '',
                required: true,
                disabled: false,
            },
        ]
    }
]

export {investProductTypeMapping}