const formDataDummy = {
    companyFullName: "Tech Innovations Inc.",
    companyOneLiner: "Innovating the future of tech.",
    companyWebsite: "https://www.techinnovations.com",
    resgisteredAus: 'true',
    sector: "Technology",
    abn: "12345678901",
    companyStreetAddress: "123 Innovation Lane",
    companySuburb: "Tech City",
    companyState: "NSW",
    companyPostcode: "2000",
    acn: "987654321",
    // companyLogoId: [{index: 0, fileName :"logo123.png "}],
    // supportingImages: ["image1.png", "image2.png", "image3.png"],
    // heroImageId: [{index: 0, fileName : "hero123.png"}],
    instagramUrl: "https://www.instagram.com/techinnovations",
    linkedinUrl: "https://www.linkedin.com/company/techinnovations",
    twitterUrl: "https://www.twitter.com/techinnovations",
    facebookUrl: "https://www.facebook.com/techinnovations",
    videoUrl: "https://www.youtube.com/watch?v=example",
    youtubeUrl: "https://www.youtube.com/techinnovations",
    companyOverview: "Tech Innovations Inc. is at the forefront of technology development, revolutionizing industries.",
    problemOrOpp: "Addressing the gap in tech advancements.",
    solution: "Providing cutting-edge tech solutions.",
    differentiation: "Unique approach to innovation.",
    intellectualProperty: "Patent-pending technology.",
    totalAddressableMarket: "Billions of potential users worldwide.",
    progress: "Secured major partnerships and funding.",
    // consentToIndividuals: 'true',
    raiseManagerContact: "manager@techinnovations.com",
    growthPlan: "Aggressive growth strategy targeting key markets.",
    // growthPlanFileId: [{index: 0, fileName :"growth123"}],
    businessStrategy: "Long-term strategic planning.",
    // businessStrategyFileId: [{index: 0, fileName :"strategy123"}],
    businessModel: "Subscription-based model.",
    // businessModelFileId: [{index: 0, fileName :"model123"}],
    orgStructure: "Flat organizational structure.",
    // orgStructureFileId: [{index: 0, fileName :"org123"}],
    proprietaryCompany: 'true',
    publicCompany: 'false',
    financialInformation: "Detailed financial projections.",
    financialInformationUrl: "https://www.techinnovations.com/financials",
    // financialInformationFileid: [{index: 0, fileName :"financials123"}],
    // capitalStructureFileId: [{index: 0, fileName :"capital123"}],
    debtFunding: "Secured debt funding.",
    // debtFundingFileId: [{index: 0, fileName :"debt123"}],
    fundsRaisedToDate: "5M",
    legalOrDisciplanryActions: "None",
    risksFacingBusiness: "Market volatility.",
    // optionalUploadForAnnexureFileId: [{index: 0, fileName :"annexure123"}],
    stage: "Seed",
    // plannedUseOfFundsFileId: [{index: 0, fileName :"funds123"}],
    privateOfferLaunchDate: "2023-01-01",
    // publicLaunchDate: "2023-06-01",
    offerCloseDate: "2023-12-31",
    investType: "Retail",
    investProductType: "Shares",
    valuation: "5000000.00",
    numberOfShares: "1000000",
    rightsAssociatedWithShares: "Voting rights.",
    // rightsAssociatedWithSharesFileId: [{index: 0, fileName :"rights123"}],
    detailsOfPreviousCsfOffers: "N/A",
    targetAmount: "10000000",
    minTarget: "1000000",
    maxTarget: "20000000",
    minInvestAmount: "250",
    // optionalUploadForAnnexureFileId2 : [{index: 0, fileName :'annexure2123'}],
    termsAndConditions: [],
    founderSignOff: "John Doe"
};

export { formDataDummy };